name: Staging Deployment

on:
  push:
    branches:
      - develop

jobs:
  deploy-backend:
    name: Deploy Backend to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy Backend
        env:
          SERVER: ${{ secrets.STAGING_SERVER }}
          USER: ${{ secrets.STAGING_USER }}
        run: |
          cd backend
          ./gradlew bootJar
          scp build/libs/*.jar $USER@$SERVER:/staging/backend
          ssh $USER@$SERVER "cd /staging/backend && java -jar backend.jar"

  deploy-frontend:
    name: Deploy Frontend to Staging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy Frontend
        env:
          SERVER: ${{ secrets.STAGING_SERVER }}
          USER: ${{ secrets.STAGING_USER }}
        run: |
          cd frontend
          npm install
          npm run build
          rsync -avz .next/ $USER@$SERVER:/staging/frontend

  qa-approval:
    name: Manual QA Approval
    needs: [deploy-backend, deploy-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Request QA Approval
        run: echo "Awaiting QA approval. Validate at staging.example.com"
      - name: Approve Workflow
        uses: hmarr/auto-approve-action@v3
